### ISSUE TITLE
OsArchTuple

### ISSUE THREAD

**Issue by scttcper** [theli-ua/hondiff#1]
Hi Theli, hope you can help me out with the OsArchTuple in fetcher.py.

It looks like it wants something to already be present, possibly a version number, in the database. Wondering what that is and how you're loading it in.

```
 File "/Users/scottc/hondiff/fetcher.py", line 30, in ARCHS
RETAIL_TUPLE = '/'.join([retail.os,retail.arch])
AttributeError: 'NoneType' object has no attribute 'os'
```

If you could help me get started, I'd appreciate it.

**Comment by scttcper** [comment]
Assuming the update variables are related.

ARRAY:
  0, ARRAY:
    version, STRING: 3.3.3
    os, STRING: mac
    arch, STRING: universal
    url, STRING: http://dl.heroesofnewerth.com/
    url2, STRING: http://patch.hon.s2games.com/
    latest_version, STRING: 3.3.3
    latest_manifest_checksum, STRING: e1f4a0d4ff252593d6a2f1fe0622dd98ecb9739c
    latest_manifest_size, STRING: 1442978
  version, STRING: 3.3.3.0
  current_version, STRING: 3.2.7.1
  current_manifest_checksum, STRING: ac97d4827ce3080f1ed8d0523e969022f4f6f6e5
  current_manifest_size, STRING: 1343935

**Comment by theli-ua** [comment]
well, yeah
they are eg:
mac, universal    for mac retail
wac, i686            for win retail

I moved them from being hardcoded to DB since hondiff.appspot.com also has sections for rct and sbt and those are not supposed to be publicly available
